feat(embed-jsx): add data validation
sapphire-community/utilities pull request #108
Opened 2021-04-20 14:00 UTC by PyroTechniac

Adds data validation to embed, hopefully creating easier-to-debug error messages

2021-04-20 14:43 UTC, PyroTechniac commented
Haven't written tests for it yet but final version is done, other than bug fixes and tweaks from reviews

2021-04-21 08:32 UTC, Favna reviewed
This is pretty cool

2021-04-21 08:32 UTC, Favna approved these changes

2021-04-21 09:31 UTC, vladfrangu requested changes

2021-04-21 09:31 UTC, vladfrangu commented on packages/embed-jsx/tests/basic.test.tsx
> +test('return an emebd with a title and url', () => {
```suggestion
test('return an embed with a title and url', () => {
```

2021-04-21 11:03 UTC, vladfrangu approved these changes

2021-04-21 12:16 UTC, vladfrangu approved these changes

2021-04-21 12:19 UTC, merged